//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapsLockIndicatorV3 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapsLockIndicatorV3.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0} | Copyright {1} ähnelt.
        /// </summary>
        internal static string aboutTextFormat {
            get {
                return ResourceManager.GetString("aboutTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon CLIv3_Caps_Off {
            get {
                object obj = ResourceManager.GetObject("CLIv3_Caps_Off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon CLIv3_Caps_On {
            get {
                object obj = ResourceManager.GetObject("CLIv3_Caps_On", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon CLIv3_Num_Off {
            get {
                object obj = ResourceManager.GetObject("CLIv3_Num_Off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon CLIv3_Num_On {
            get {
                object obj = ResourceManager.GetObject("CLIv3_Num_On", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon CLIv3_Scroll_Off {
            get {
                object obj = ResourceManager.GetObject("CLIv3_Scroll_Off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon CLIv3_Scroll_On {
            get {
                object obj = ResourceManager.GetObject("CLIv3_Scroll_On", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die b:numIco=True
        ///b:capsIco=True
        ///b:scrollIco=True
        ///b:numInd=True
        ///b:capsInd=True
        ///b:scrollInd=True
        ///b:keybInd=True
        ///b:noIco=False
        ///b:noInd=False
        ///b:darkMode=False
        ///b:hideOnStartup=False
        ///b:checkForUpdates=True
        ///b:upgradeRequired=True
        ///b:alwaysShowWhenActive=False
        ///b:firstRun=True
        ///b:searchForUpdatesAfterResume=True
        ///b:showNotificationOnAllScreens=False
        ///b:supressEOLMessage=False
        ///b:dontOverwriteApplicationOnUpdate=False
        ///b:persistentOverlayCapsOff=False
        ///b:persistentOverlayCapsOn=False
        ///b:persistentOverlayNumOff=False
        ///b:persisten [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string defaultSettings {
            get {
                return ResourceManager.GetString("defaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon settings_dark {
            get {
                object obj = ResourceManager.GetObject("settings_dark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die numIco								Show icon for num lock
        ///capsIco								Show icon for caps lock
        ///scrollIco							Show icon for scroll lock
        ///numInd								Show notification for num lock
        ///capsInd								Show notification for caps lock
        ///scrollInd							Show notification for scroll lock
        ///noIco								Don&apos;t show icons
        ///noInd								Don&apos;t show notifications
        ///darkMode							Enable dark color scheme (Has no effect on anything below Windows 10)
        ///hideOnStartup						Hide ImeModeIndicator on startup
        ///checkForUpdates						Automatically check for up [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string settingsDescriptions {
            get {
                return ResourceManager.GetString("settingsDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TabIcons {
            get {
                object obj = ResourceManager.GetObject("TabIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
