//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapsLockIndicatorV3 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapsLockIndicatorV3.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background colour activated ähnelt.
        /// </summary>
        internal static string backgroundColourActivatedButton {
            get {
                return ResourceManager.GetString("backgroundColourActivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background colour deactivated ähnelt.
        /// </summary>
        internal static string backgroundColourDeactivatedButton {
            get {
                return ResourceManager.GetString("backgroundColourDeactivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Border colour activated ähnelt.
        /// </summary>
        internal static string borderColourActivatedButton {
            get {
                return ResourceManager.GetString("borderColourActivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Border colour deactivated ähnelt.
        /// </summary>
        internal static string borderColourDeactivatedButton {
            get {
                return ResourceManager.GetString("borderColourDeactivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caps lock ähnelt.
        /// </summary>
        internal static string capsLock {
            get {
                return ResourceManager.GetString("capsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for &amp;updates ähnelt.
        /// </summary>
        internal static string checkForUpdates {
            get {
                return ResourceManager.GetString("checkForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking for updates... ähnelt.
        /// </summary>
        internal static string checkingForUpdates {
            get {
                return ResourceManager.GetString("checkingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colours ähnelt.
        /// </summary>
        internal static string coloursGroup {
            get {
                return ResourceManager.GetString("coloursGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Exit ähnelt.
        /// </summary>
        internal static string contextMenuExit {
            get {
                return ResourceManager.GetString("contextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Show ähnelt.
        /// </summary>
        internal static string contextMenuShow {
            get {
                return ResourceManager.GetString("contextMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Dismiss ähnelt.
        /// </summary>
        internal static string dismissButton {
            get {
                return ResourceManager.GetString("dismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display time ähnelt.
        /// </summary>
        internal static string displayTime {
            get {
                return ResourceManager.GetString("displayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download &amp;manually ähnelt.
        /// </summary>
        internal static string downloadManuallyButton {
            get {
                return ResourceManager.GetString("downloadManuallyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download more translations... ähnelt.
        /// </summary>
        internal static string downloadMoreTranslations {
            get {
                return ResourceManager.GetString("downloadMoreTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Exit Application ähnelt.
        /// </summary>
        internal static string exitApplication {
            get {
                return ResourceManager.GetString("exitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exiting the application means the icons and notifications are no longer displayed. Exit anyway? ähnelt.
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font ähnelt.
        /// </summary>
        internal static string fontGroup {
            get {
                return ResourceManager.GetString("fontGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text colour activated ähnelt.
        /// </summary>
        internal static string foregroundColourActivatedButton {
            get {
                return ResourceManager.GetString("foregroundColourActivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text colour deactivated ähnelt.
        /// </summary>
        internal static string foregroundColourDeactivatedButton {
            get {
                return ResourceManager.GetString("foregroundColourDeactivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can show CapsLock Indicator again by double clicking on this icon. ähnelt.
        /// </summary>
        internal static string generalIconBalloonText {
            get {
                return ResourceManager.GetString("generalIconBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide on start up ähnelt.
        /// </summary>
        internal static string hideOnStartup {
            get {
                return ResourceManager.GetString("hideOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Hide window ähnelt.
        /// </summary>
        internal static string hideWindow {
            get {
                return ResourceManager.GetString("hideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} changed ähnelt.
        /// </summary>
        internal static string keyChanged {
            get {
                return ResourceManager.GetString("keyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is off ähnelt.
        /// </summary>
        internal static string keyIsOff {
            get {
                return ResourceManager.GetString("keyIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} is on ähnelt.
        /// </summary>
        internal static string keyIsOn {
            get {
                return ResourceManager.GetString("keyIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Notification settings ähnelt.
        /// </summary>
        internal static string notificationSettings {
            get {
                return ResourceManager.GetString("notificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notification Settings ähnelt.
        /// </summary>
        internal static string notificationSettingsTitle {
            get {
                return ResourceManager.GetString("notificationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Num lock ähnelt.
        /// </summary>
        internal static string numLock {
            get {
                return ResourceManager.GetString("numLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opacity ähnelt.
        /// </summary>
        internal static string opacity {
            get {
                return ResourceManager.GetString("opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overlay position ähnelt.
        /// </summary>
        internal static string overlayPositionGroup {
            get {
                return ResourceManager.GetString("overlayPositionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permanently ähnelt.
        /// </summary>
        internal static string permanentIndicator {
            get {
                return ResourceManager.GetString("permanentIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save &amp;&amp; close ähnelt.
        /// </summary>
        internal static string saveAndCloseButton {
            get {
                return ResourceManager.GetString("saveAndCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scroll lock ähnelt.
        /// </summary>
        internal static string scrollLock {
            get {
                return ResourceManager.GetString("scrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show icons for... ähnelt.
        /// </summary>
        internal static string showIconsFor {
            get {
                return ResourceManager.GetString("showIconsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show no icons ähnelt.
        /// </summary>
        internal static string showNoIcons {
            get {
                return ResourceManager.GetString("showNoIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show no notification ähnelt.
        /// </summary>
        internal static string showNoNotification {
            get {
                return ResourceManager.GetString("showNoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show notification when... ähnelt.
        /// </summary>
        internal static string showNotificationWhen {
            get {
                return ResourceManager.GetString("showNotificationWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start on logon ähnelt.
        /// </summary>
        internal static string startOnLogon {
            get {
                return ResourceManager.GetString("startOnLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CapsLock Indicator Update available! ähnelt.
        /// </summary>
        internal static string updateAvailable {
            get {
                return ResourceManager.GetString("updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0}, released {1} ähnelt.
        /// </summary>
        internal static string updateInfoFormat {
            get {
                return ResourceManager.GetString("updateInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Update now ähnelt.
        /// </summary>
        internal static string updateNow {
            get {
                return ResourceManager.GetString("updateNow", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Icon tooltip for Caps Lock
        /// </summary>
        internal static string capsLockIcon {
            get {
                return ResourceManager.GetString("capsLockIcon", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Icon tooltip for Num Lock
        /// </summary>
        internal static string numLockIcon {
            get {
                return ResourceManager.GetString("numLockIcon", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Icon tooltip for Scroll Lock
        /// </summary>
        internal static string scrollLockIcon {
            get {
                return ResourceManager.GetString("scrollLockIcon", resourceCulture);
            }
        }
    }
}
