//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapsLockIndicatorV3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapsLockIndicatorV3.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background colour activated.
        /// </summary>
        internal static string backgroundColourActivatedButton {
            get {
                return ResourceManager.GetString("backgroundColourActivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background colour deactivated.
        /// </summary>
        internal static string backgroundColourDeactivatedButton {
            get {
                return ResourceManager.GetString("backgroundColourDeactivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border colour activated.
        /// </summary>
        internal static string borderColourActivatedButton {
            get {
                return ResourceManager.GetString("borderColourActivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border colour deactivated.
        /// </summary>
        internal static string borderColourDeactivatedButton {
            get {
                return ResourceManager.GetString("borderColourDeactivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps lock.
        /// </summary>
        internal static string capsLock {
            get {
                return ResourceManager.GetString("capsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for &amp;updates.
        /// </summary>
        internal static string checkForUpdates {
            get {
                return ResourceManager.GetString("checkForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string checkingForUpdates {
            get {
                return ResourceManager.GetString("checkingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colours.
        /// </summary>
        internal static string coloursGroup {
            get {
                return ResourceManager.GetString("coloursGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string contextMenuExit {
            get {
                return ResourceManager.GetString("contextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        internal static string contextMenuHide {
            get {
                return ResourceManager.GetString("contextMenuHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Show.
        /// </summary>
        internal static string contextMenuShow {
            get {
                return ResourceManager.GetString("contextMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dismiss.
        /// </summary>
        internal static string dismissButton {
            get {
                return ResourceManager.GetString("dismissButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display time.
        /// </summary>
        internal static string displayTime {
            get {
                return ResourceManager.GetString("displayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download &amp;manually.
        /// </summary>
        internal static string downloadManuallyButton {
            get {
                return ResourceManager.GetString("downloadManuallyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download more translations....
        /// </summary>
        internal static string downloadMoreTranslations {
            get {
                return ResourceManager.GetString("downloadMoreTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit Application.
        /// </summary>
        internal static string exitApplication {
            get {
                return ResourceManager.GetString("exitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting the application means the icons and notifications are no longer displayed. Exit anyway?.
        /// </summary>
        internal static string exitMessage {
            get {
                return ResourceManager.GetString("exitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string fontGroup {
            get {
                return ResourceManager.GetString("fontGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text colour activated.
        /// </summary>
        internal static string foregroundColourActivatedButton {
            get {
                return ResourceManager.GetString("foregroundColourActivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text colour deactivated.
        /// </summary>
        internal static string foregroundColourDeactivatedButton {
            get {
                return ResourceManager.GetString("foregroundColourDeactivatedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can show CapsLock Indicator again by double clicking on this icon..
        /// </summary>
        internal static string generalIconBalloonText {
            get {
                return ResourceManager.GetString("generalIconBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on start up.
        /// </summary>
        internal static string hideOnStartup {
            get {
                return ResourceManager.GetString("hideOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide window.
        /// </summary>
        internal static string hideWindow {
            get {
                return ResourceManager.GetString("hideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed.
        /// </summary>
        internal static string keyChanged {
            get {
                return ResourceManager.GetString("keyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is off.
        /// </summary>
        internal static string keyIsOff {
            get {
                return ResourceManager.GetString("keyIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is on.
        /// </summary>
        internal static string keyIsOn {
            get {
                return ResourceManager.GetString("keyIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Notification settings.
        /// </summary>
        internal static string notificationSettings {
            get {
                return ResourceManager.GetString("notificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        internal static string notificationSettingsTitle {
            get {
                return ResourceManager.GetString("notificationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num lock.
        /// </summary>
        internal static string numLock {
            get {
                return ResourceManager.GetString("numLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string opacity {
            get {
                return ResourceManager.GetString("opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay position.
        /// </summary>
        internal static string overlayPositionGroup {
            get {
                return ResourceManager.GetString("overlayPositionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently.
        /// </summary>
        internal static string permanentIndicator {
            get {
                return ResourceManager.GetString("permanentIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save &amp;&amp; close.
        /// </summary>
        internal static string saveAndCloseButton {
            get {
                return ResourceManager.GetString("saveAndCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll lock.
        /// </summary>
        internal static string scrollLock {
            get {
                return ResourceManager.GetString("scrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icons for....
        /// </summary>
        internal static string showIconsFor {
            get {
                return ResourceManager.GetString("showIconsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show no icons.
        /// </summary>
        internal static string showNoIcons {
            get {
                return ResourceManager.GetString("showNoIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show no notification.
        /// </summary>
        internal static string showNoNotification {
            get {
                return ResourceManager.GetString("showNoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification when....
        /// </summary>
        internal static string showNotificationWhen {
            get {
                return ResourceManager.GetString("showNotificationWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on logon.
        /// </summary>
        internal static string startOnLogon {
            get {
                return ResourceManager.GetString("startOnLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapsLock Indicator Update available!.
        /// </summary>
        internal static string updateAvailable {
            get {
                return ResourceManager.GetString("updateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}, released {1}.
        /// </summary>
        internal static string updateInfoFormat {
            get {
                return ResourceManager.GetString("updateInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update now.
        /// </summary>
        internal static string updateNow {
            get {
                return ResourceManager.GetString("updateNow", resourceCulture);
            }
        }
    }
}
