//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapsLockIndicatorV3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool numIco {
            get {
                return ((bool)(this["numIco"]));
            }
            set {
                this["numIco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool capsIco {
            get {
                return ((bool)(this["capsIco"]));
            }
            set {
                this["capsIco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool scrollIco {
            get {
                return ((bool)(this["scrollIco"]));
            }
            set {
                this["scrollIco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool numInd {
            get {
                return ((bool)(this["numInd"]));
            }
            set {
                this["numInd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool capsInd {
            get {
                return ((bool)(this["capsInd"]));
            }
            set {
                this["capsInd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool scrollInd {
            get {
                return ((bool)(this["scrollInd"]));
            }
            set {
                this["scrollInd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool noIco {
            get {
                return ((bool)(this["noIco"]));
            }
            set {
                this["noIco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool noInd {
            get {
                return ((bool)(this["noInd"]));
            }
            set {
                this["noInd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool beta_enableDarkMode {
            get {
                return ((bool)(this["beta_enableDarkMode"]));
            }
            set {
                this["beta_enableDarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int indDisplayTime {
            get {
                return ((int)(this["indDisplayTime"]));
            }
            set {
                this["indDisplayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66, 66, 66")]
        public global::System.Drawing.Color indBgColourActive {
            get {
                return ((global::System.Drawing.Color)(this["indBgColourActive"]));
            }
            set {
                this["indBgColourActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color indFgColourActive {
            get {
                return ((global::System.Drawing.Color)(this["indFgColourActive"]));
            }
            set {
                this["indFgColourActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("77, 180, 52")]
        public global::System.Drawing.Color indBdColourActive {
            get {
                return ((global::System.Drawing.Color)(this["indBdColourActive"]));
            }
            set {
                this["indBdColourActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.4.0.0")]
        public string versionNo {
            get {
                return ((string)(this["versionNo"]));
            }
            set {
                this["versionNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hideOnStartup {
            get {
                return ((bool)(this["hideOnStartup"]));
            }
            set {
                this["hideOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 12pt")]
        public global::System.Drawing.Font indFont {
            get {
                return ((global::System.Drawing.Font)(this["indFont"]));
            }
            set {
                this["indFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66, 66, 66")]
        public global::System.Drawing.Color indBgColourInactive {
            get {
                return ((global::System.Drawing.Color)(this["indBgColourInactive"]));
            }
            set {
                this["indBgColourInactive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color indFgColourInactive {
            get {
                return ((global::System.Drawing.Color)(this["indFgColourInactive"]));
            }
            set {
                this["indFgColourInactive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180, 52, 77")]
        public global::System.Drawing.Color indBdColourInactive {
            get {
                return ((global::System.Drawing.Color)(this["indBdColourInactive"]));
            }
            set {
                this["indBdColourInactive"] = value;
            }
        }
    }
}
